substitutions:
  device: esp_matrix_lamp
  name: ESPHome Matrix Lamp
  location: ${name}
  update_interval: 60s
  device_ip: 192.168.0.0
  reboot_timeout: 0s
  num_leds: "256"
  type_leds: "GRB"
  pin_leds: "GPIO3"
  color_correct_bright: "70%"
  comment: "ESPHome Matrix Lamp"

esphome:
  name: ${device}
  comment: $comment
  build_path: ./.build/$device
  project:
    name: $project_name
    version: $project_version
  <<: !include common/boot/window_illumination.yaml

<<: !include common/esp/esp32_node.yaml

<<: !include common/common.yaml

packages:
  common: !include packages/common_32.yaml
  light: !include packages/light_matrix_lamp.yaml
