substitutions:
  device: esp_sound_reactive_hyperion
  name: Sound Reactive Hyperion
  location: ${name}
  update_interval: 3s
  device_ip: 192.168.0.0
  reboot_timeout: 0s
  num_leds: "300"
  type_leds: "GRB"
  flagflip: "0"
  pin_leds: "GPIO16"
  color_correct_bright: "50%"
  sunrise: "600"  # 10 Minutes
  sunrize_bright: "255"  # Max brightness 0..255
  comment: "Window Illumination with Sound Reactive and Hyperion effects"

esphome:
  name: ${device}
  comment: $comment
  build_path: ./.build/$device
  project:
    name: $project_name
    version: $project_version
  <<: !include common/boot/window_illumination.yaml

<<: !include common/esp/esp32_wrover.yaml

<<: !include common/common.yaml

packages:
  common: !include packages/common_32.yaml
  led_power: !include packages/led_power.yaml
  light: !include packages/light_sound_reactive_hyperion.yaml
