substitutions:
  device: esp_fastled
  name: Fastled Effects
  location: ${name}
  update_interval: 3s
  device_ip: 192.168.0.0
  reboot_timeout: 0s
  num_leds: "300"
  type_leds: "GRB"
  flagflip: "0"
  pin_leds: "GPIO16"
  color_correct_bright: "50%"
  sunrise: "100"
  project_name: "ajs.led_light"
  project_version: "1.0.5"
  comment: "Window Illumination with FastLed effects"

esphome:
  name: ${device}
  comment: $comment
  build_path: ./.build/$device
  project:
    name: $project_name
    version: $project_version
  libraries:
    - "FastLED"
  includes:
    - includes/light/light.h
    - includes/light/palettes.h
  <<: !include common/boot/window_illumination.yaml

<<: !include common/esp/esp32_node.yaml

<<: !include common/common.yaml

packages:
  common: !include packages/common_32.yaml
  led_power: !include packages/led_power.yaml

number:
  # FastLed Settings
  - !include common/number/fastled_speed.yaml
  - !include common/number/fastled_variant.yaml
  - !include common/number/fastled_palette.yaml

light:
  # Neopixel
  - !include common/light/neopixel_illumination_fastled.yaml
