substitutions:
  name: "esp-svitlobot"
  friendly_name: "Svitlo Bot"

dashboard_import:
  package_import_url: github://andrewjswan/esphome-config/svitlobot.yaml@main

esp32:
  board: nodemcu-32s
  # framework:
  #   type: esp-idf

remote_package_files:
  url: https://github.com/andrewjswan/svitlobot
  files:
    - packages/esp32.yaml
    - packages/common.yaml
    - packages/svitlobot.yaml
  ref: main
  refresh: 30s
