substitutions:
  project_name: "ajs.Light - Sound Reactive - Hyperion"
  project_version: "1.5.5"

esphome:
  libraries:
    - fastled/FastLED @ 3.6.0
    - arduinoFFT=https://github.com/kosme/arduinoFFT.git
  includes:
    - includes/light/light.h
    - includes/light/stars.h
    - includes/light/gamma.h
    - includes/light/palettes.h
    - includes/sound/music_leds_esphome.h
    - includes/sound/VisualEffect.h
    - includes/sound/audio_source.h
    - includes/sound/audio_reactive.h

external_components:
  - source:
      type: git
      url: https://github.com/KaufHA/common
    components: [ddp]

ddp:

# Over The Air Update Component
ota:
  on_begin:
    then:
      - lambda: |-
          music_leds.~MusicLeds();

number:
  # FastLed Settings
  - !include ../common/number/fastled_speed.yaml
  - !include ../common/number/fastled_variant.yaml
  - !include ../common/number/fastled_palette.yaml

light:
  # Neopixel with Sound Reactive and Hyperion
  - !include ../common/light/neopixel_illumination_sound_hyperion.yaml
