substitutions:
  project_name: "ajs.Light - Fastled"
  project_version: "1.0.5"

esphome:
  libraries:
    - fastled/FastLED @ 3.6.0
  includes:
    - includes/light/light.h
    - includes/light/palettes.h

number:
  # FastLed Settings
  - !include ../common/number/fastled_speed.yaml
  - !include ../common/number/fastled_variant.yaml
  - !include ../common/number/fastled_palette.yaml

light:
  # Neopixel with FastLed effects
  - !include ../common/light/neopixel_illumination_fastled.yaml
