substitutions:
  project_name: "ajs.Light - Matrix Lamp"
  project_version: "1.1.5"

esphome:
  libraries:
    - fastled/FastLED @ 3.6.0
  includes:
    - includes/matrix_lamp/light.h
    - includes/matrix_lamp/constants.h
    - includes/matrix_lamp/utility.h
    - includes/matrix_lamp/effect_ticker.h
    - includes/matrix_lamp/effects.h
    - includes/matrix_lamp/noise_effects.h
    - includes/matrix_lamp/matrix_lamp.h

# Over The Air Update Component
ota:
  on_begin:
    then:
      - lambda: |-
          matrix_lamp.~GyverLamp();

number:
  # FastLed Settings
  - !include ../common/number/fastled_speed.yaml
  - !include ../common/number/fastled_variant.yaml
  - !include ../common/number/fastled_palette.yaml

light:
  # Neopixel with Matrix Lamp
  - !include ../common/light/neopixel_matrix_lamp.yaml
